"""Create DB

Revision ID: db9820ca2f58
Revises: 
Create Date: 2019-03-16 21:15:13.754980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db9820ca2f58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hieroglyph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hieroglyph', sa.String(length=1), nullable=True),
    sa.Column('onyomi', postgresql.JSON, nullable=True),
    sa.Column('kunyomi', postgresql.JSON, nullable=True),
    sa.Column('translation', postgresql.JSON, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hieroglyph')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('hieroglyph')
    # ### end Alembic commands ###
